### PR TITLE
fix

### LINKED ISSUE #9: Changeset link continuously appear during download
chnageset_id

<details>

```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-08-15 01:49:02 +0200 (Mon, 15 Aug 2016)
Build-Date:2016-08-15 01:33:35
Revision:10799
Relative:URL: ^/trunk

Identification: JOSM/1.5 (10799 en) Mac OS X 10.11.6
Memory Usage: 801 MB / 1820 MB (495 MB allocated, but free)
Java version: 1.8.0_60-b27, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
VM arguments: [-Djosm.pref=<josm.pref>/]
Dataset consistency test: No problems found

Plugins:
+ BuildingGeneralization (1010)
+ CommandLine (32796)
+ DirectDownload (32699)
+ DirectUpload (32699)
+ FastDraw (32773)
+ apache-commons (32699)
+ auto_tools (1468620578)
+ buildings_tools (32796)
+ changesetID (1461665161)
+ continuosDownload (53)
+ dataimport (32699)
+ ext_tools (32796)
+ gpxfilter (32699)
+ measurement (32732)
+ michigan_left (32699)
+ photo_geotagging (32699)
+ reverter (32796)
+ terracer (32699)
+ todo (29154)
+ turnlanes-tagging (1470950886)
+ utilsplugin2 (32815)

Tagging presets:
+ https://josm.openstreetmap.de/josmfile?page=Presets/LaneAttributes&zip=1

Map paint styles:
- https://github.com/hotosm/HDM-JOSM-style/archive/master.zip
+ https://github.com/gmgeo/osmic-josm-style/archive/master.zip
+ https://josm.openstreetmap.de/josmfile?page=Styles/LessObtrusiveNodes&zip=1
- https://raw.githubusercontent.com/Andygol/josm-styles/master/created_in_2015.mapcss
+ ${HOME}/osm/version.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Sidewalks&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
- https://raw.githubusercontent.com/species/josm-preset-traffic_sign_direction/master/direction.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features_ryg&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_buildings&zip=1

Validator rules:
+ https://gist.githubusercontent.com/<user.name>/80414b47cdf160710287bf99e208b552/raw/4d429639e43de18da58d669f595844eb43faf86a/labuilding.mapcss

Last errors/warnings:
- W: Failed to scan file 'josm-geojson.jar.new' for plugin information. Skipping.
- W: Unable to delete file <josm.cache>/tiles/TMS.key
- W: Unable to delete file <josm.cache>/tiles/TMS.data
- E: Skipping to the next rule, because of an error:
- E: org.openstreetmap.josm.gui.mappaint.mapcss.parsergen.ParseException: Encountered " ":" ": "" at line 3, column 14.
- W: Failed to add https://gist.githubusercontent.com/<user.name>/80414b47cdf160710287bf99e208b552/raw/4d429639e43de18da58d669f595844eb43faf86a/labuilding.mapcss to tag checker
- W: org.openstreetmap.josm.gui.mappaint.mapcss.parsergen.ParseException: Encountered " "}" "} "" at line 6, column 4.
- W: Old style SideButton usage for action org.openstreetmap.josm.gui.io.CredentialDialog$OKAction@2863c200
- W: Old style SideButton usage for action org.openstreetmap.josm.gui.io.CredentialDialog$CancelAction@220d8772
- W: Old style SideButton usage for action org.openstreetmap.josm.gui.help.ContextSensitiveHelpAction@397ba2a6

...

}}}
```

</details>

### PR DESCRIPTION
**Pull request by aarthykc**
fixes #9 
cc @maning

### CODE REVIEW

**Comment by maning** [comment]
jar file?

**Comment by aarthykc** [comment]
@maning, it's in the readme

**Comment by maning** [comment]
It points to the [3.0 release](https://github.com/aarthykc/changesetID/releases/tag/3.0).  Should I compile?

**Comment by aarthykc** [comment]
@maning, sorry, seems like the jar didn't get properly uploaded last night! have updated the release with the jar ^_^

**Pull request merged**
